In [4]:
# !pip install openpyxl

In [14]:
import pandas as pd
import numpy as np

In [40]:
df = pd.ExcelFile('Sales.xlsx')

In [41]:
df.sheet_names

['Data Dict', 'Sales']

In [42]:
df = df.parse('Sales')

In [43]:
df.head()

,CustID,AgentBonus,Age,CustTenure,Channel,Occupation,EducationField,Gender,ExistingProdType,Designation,NumberOfPolicy,MaritalStatus,MonthlyIncome,Complaint,ExistingPolicyTenure,SumAssured,Zone,PaymentMethod,LastMonthCalls,CustCareScore
0,7000000,4409,22.0,4.0,Agent,Salaried,Graduate,Female,3,Manager,2.0,Single,20993.0,1,2.0,806761.0,North,Half Yearly,5,2.0
1,7000001,2214,11.0,2.0,Third Party Partner,Salaried,Graduate,Male,4,Manager,4.0,Divorced,20130.0,0,3.0,294502.0,North,Yearly,7,3.0
2,7000002,4273,26.0,4.0,Agent,Free Lancer,Post Graduate,Male,4,Exe,3.0,Unmarried,17090.0,1,2.0,NaN,North,Yearly,0,3.0
3,7000003,1791,11.0,NaN,Third Party Partner,Salaried,Graduate,Fe male,3,Executive,3.0,Divorced,17909.0,1,2.0,268635.0,West,Half Yearly,0,5.0
4,7000004,2955,6.0,NaN,Agent,Small Business,UG,Male,3,Executive,4.0,Divorced,18468.0,0,4.0,366405.0,West,Half Yearly,2,5.0

In [44]:
df.shape

(4520, 20)

In [45]:
df.isna().sum()

CustID                    0
AgentBonus                0
Age                     269
CustTenure              226
Channel                   0
Occupation                0
EducationField            0
Gender                    0
ExistingProdType          0
Designation               0
NumberOfPolicy           45
MaritalStatus             0
MonthlyIncome           236
Complaint                 0
ExistingPolicyTenure    184
SumAssured              154
Zone                      0
PaymentMethod             0
LastMonthCalls            0
CustCareScore            52
dtype: int64

In [46]:
# df.dropna(thresh=10)

In [47]:
np.unique(df['Age'])

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
       28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40.,
       41., 42., 43., 44., 46., 47., 48., 50., 51., 52., 53., 54., 57.,
       58., nan])

In [48]:
# pd.value_counts(df['Age'])
# pd.value_counts(df['CustTenure'])
# pd.value_counts(df['NumberOfPolicy'])
# pd.value_counts(df['MonthlyIncome'])
# pd.value_counts(df['ExistingPolicyTenure'])
# pd.value_counts(df['SumAssured'])
pd.value_counts(df['CustCareScore'])

3.0    1367
1.0     928
5.0     893
4.0     826
2.0     454
Name: CustCareScore, dtype: int64

In [49]:
df['Age'].fillna(df['Age'].median(), inplace=True)

In [50]:
df['CustTenure'].fillna(df['CustTenure'].median(), inplace=True)

In [58]:
df['NumberOfPolicy'].fillna(df['NumberOfPolicy'].mode().values[0], inplace=True)

In [52]:
df['MonthlyIncome'].fillna(df['MonthlyIncome'].mean(), inplace=True)

In [53]:
df['ExistingPolicyTenure'].fillna(df['ExistingPolicyTenure'].mean(), inplace=True)

In [54]:
df['SumAssured'].fillna(df['SumAssured'].mean(), inplace=True)

In [59]:
df['CustCareScore'].fillna(df['CustCareScore'].mode().values[0], inplace=True)

In [60]:
df.isna().sum()

CustID                  0
AgentBonus              0
Age                     0
CustTenure              0
Channel                 0
Occupation              0
EducationField          0
Gender                  0
ExistingProdType        0
Designation             0
NumberOfPolicy          0
MaritalStatus           0
MonthlyIncome           0
Complaint               0
ExistingPolicyTenure    0
SumAssured              0
Zone                    0
PaymentMethod           0
LastMonthCalls          0
CustCareScore           0
dtype: int64

In [39]:
pd.value_counts(df['NumberOfPolicy'])

4.0    1094
3.0     939
5.0     856
2.0     711
1.0     438
6.0     437
Name: NumberOfPolicy, dtype: int64

In [57]:
df['NumberOfPolicy'].mode()

0    4.0
Name: NumberOfPolicy, dtype: float64

In [61]:
df.head()

,CustID,AgentBonus,Age,CustTenure,Channel,Occupation,EducationField,Gender,ExistingProdType,Designation,NumberOfPolicy,MaritalStatus,MonthlyIncome,Complaint,ExistingPolicyTenure,SumAssured,Zone,PaymentMethod,LastMonthCalls,CustCareScore
0,7000000,4409,22.0,4.0,Agent,Salaried,Graduate,Female,3,Manager,2.0,Single,20993.0,1,2.0,806761.000000,North,Half Yearly,5,2.0
1,7000001,2214,11.0,2.0,Third Party Partner,Salaried,Graduate,Male,4,Manager,4.0,Divorced,20130.0,0,3.0,294502.000000,North,Yearly,7,3.0
2,7000002,4273,26.0,4.0,Agent,Free Lancer,Post Graduate,Male,4,Exe,3.0,Unmarried,17090.0,1,2.0,619999.699267,North,Yearly,0,3.0
3,7000003,1791,11.0,13.0,Third Party Partner,Salaried,Graduate,Fe male,3,Executive,3.0,Divorced,17909.0,1,2.0,268635.000000,West,Half Yearly,0,5.0
4,7000004,2955,6.0,13.0,Agent,Small Business,UG,Male,3,Executive,4.0,Divorced,18468.0,0,4.0,366405.000000,West,Half Yearly,2,5.0

In [62]:
df.corr()

,CustID,AgentBonus,Age,CustTenure,ExistingProdType,NumberOfPolicy,MonthlyIncome,Complaint,ExistingPolicyTenure,SumAssured,LastMonthCalls,CustCareScore
CustID,1.000000,0.192393,0.093616,0.113619,0.419359,0.254446,0.299582,0.001921,0.102233,0.161167,0.122144,-0.034245
AgentBonus,0.192393,1.000000,0.552344,0.555791,0.113023,0.079266,0.580498,0.014281,0.367985,0.840845,0.199708,0.023192
Age,0.093616,0.552344,1.000000,0.323486,0.073452,0.046775,0.334280,0.020257,0.203220,0.464131,0.116929,0.034263
CustTenure,0.113619,0.555791,0.323486,1.000000,0.082784,0.048699,0.326640,0.004282,0.203091,0.465377,0.117702,0.011497
ExistingProdType,0.419359,0.113023,0.073452,0.082784,1.000000,0.149862,0.192998,-0.003486,0.056074,0.101046,0.033191,0.004110
NumberOfPolicy,0.254446,0.079266,0.046775,0.048699,0.149862,1.000000,0.136025,-0.016014,0.048888,0.062395,0.075138,-0.001005
MonthlyIncome,0.299582,0.580498,0.334280,0.326640,0.192998,0.136025,1.000000,-0.004384,0.181439,0.465317,0.344251,0.035956
Complaint,0.001921,0.014281,0.020257,0.004282,-0.003486,-0.016014,-0.004384,1.000000,0.002020,-0.000252,-0.026320,-0.003814
ExistingPolicyTenure,0.102233,0.367985,0.203220,0.203091,0.056074,0.048888,0.181439,0.002020,1.000000,0.316144,0.104014,-0.005331
SumAssured,0.161167,0.840845,0.464131,0.465377,0.101046,0.062395,0.465317,-0.000252,0.316144,1.000000,0.154143,0.002884
LastMonthCalls,0.122144,0.199708,0.116929,0.117702,0.033191,0.075138,0.344251,-0.026320,0.104014,0.154143,1.000000,0.006386
CustCareScore,-0.034245,0.023192,0.034263,0.011497,0.004110,-0.001005,0.035956,-0.003814,-0.005331,0.002884,0.006386,1.000000

In [63]:
# Feature Selection - Feature Importance
# Label Encoding
# OneHot Encoding
# Feature Scaling - Normalization / Standardization
# Train and Test - KFold Cross Validation
# Grid Search / Random Search
# Suppose : Regression - Linear, Poly, Decision Tree with Ensemble Methods, Ridge